# Generated by Django 4.2.21 on 2025-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHOP', models.CharField(max_length=100)),
                ('BUDGET', models.FloatField()),
                ('OPITEMS', models.FloatField()),
                ('INVOICE', models.FloatField()),
                ('AV_BUDGET', models.FloatField()),
                ('GJAHR', models.IntegerField()),
            ],
            options={
                'db_table': 'zedw_budget_dash_v',
                'managed': False,
            },
        ),
    ]
